development:
  adapter: redis
  url: redis://:add1sen@redis-17702.c9.us-east-1-4.ec2.cloud.redislabs.com:17702

test:
  adapter: async 

production:
  adapter: redis
  url: redis://:add1sen@redis-17702.c9.us-east-1-4.ec2.cloud.redislabs.com:17702
                            
